### ISSUE TITLE
2020, 10월 5일에 작성한글의 제목이 이전 글과 동일함(Study summary 기록 2020-09-15)

### ISSUE THREAD

**Issue by jayleekr** [ADAS-study-group/adas-study-group.github.io#18]
고쳐주시기바랍니다 현호쿤

**Comment by jayleekr** [comment]
New : https://adas-study-group.github.io/posts/08YoctoProjectDev/

Old : https://adas-study-group.github.io/posts/07BitbakeMetadata/

**Comment by leehyunho94** [comment]
pr 확인 부탁드립니다.

**Comment by jayleekr** [comment]
Good
