### ISSUE TITLE
아이폰 어플로 github 이슈 OPEN

### ISSUE THREAD

**Issue by realgoodman** [ADAS-study-group/adas-study-group.github.io#51]
아이폰 어플로 github 이슈 OPEN이 되나요?

![image](https://user-images.githubusercontent.com/69847576/99403754-2b806000-292e-11eb-92a8-227121a4a4bb.jpeg)

**Comment by realgoodman** [comment]
**되네요!**

**Comment by realgoodman** [comment]
CLOSE는 Master만 되나요?
Participants는 안되나봐요!
Contributer(?)부터 되는건가요?
@jayleekr

**Comment by jayleekr** [comment]
ㅋㅋㅋ오오.. 그거까지는 모르겠네요
admin만 되는거같은데 ....

**Comment by realgoodman** [comment]
question 라벨링에 대한 코멘트입니다!
![image](https://user-images.githubusercontent.com/69847576/99595212-b13c0280-2a37-11eb-82db-7b0ce3a5ff4e.jpeg)

**Comment by realgoodman** [comment]
https://www.hahwul.com/2018/07/27/closing-git-issue-with-commit/
