### ISSUE TITLE
빌드 실패

### ISSUE THREAD

**Issue by devlee8585** [ADAS-study-group/adas-study-group.github.io#58]
bash tool/build.sh 실패
![빌드실패](https://user-images.githubusercontent.com/69380333/102013573-74440100-3d94-11eb-9826-6b986ed3d0da.png)

**Comment by jayleekr** [comment]
@leehyunho94  님 md 파일명 영어로 작성바랍니다.
파일명에는 space가 들어가선 안됩니다.
commit 하기전에 build.sh 와 run.sh 로 블로그로 확인하고 올려주세요 👎
